services:
  payments-read-model:
    container_name: "payments-read-model"
    build:
      context: "${WALLETERA_DIR}/payments-read-model/"
      no_cache: true
    develop:
      watch:
        - path: "${WALLETERA_DIR}/payments-read-model/"
          action: rebuild
    ports:
      - "4880:4880"
    depends_on:
      rabbitmq:
        condition: service_healthy
      mongodb:
        condition: service_healthy
      barong:
        condition: service_started
    environment:
      PUBLIC_API_HTTP_SERVER_PORT: 4880
      RABBITMQ_HOST: "rabbitmq"
      RABBITMQ_PASSWORD: "guest"
      RABBITMQ_PORT: 5672
      RABBITMQ_USER: "guest"
      MONGODB_URL: "mongodb://mongodb:27017/?retryWrites=true&w=majority"
      BASE64_AUTH_PUB_KEY: "LS0tLS1CRUdJTiBQVUJMSUMgS0VZLS0tLS0KTUlJQklqQU5CZ2txaGtpRzl3MEJBUUVGQUFPQ0FROEFNSUlCQ2dLQ0FRRUF1SUE3eWQ4WGozbE9uQ24wRkg1NwppVkdRQVdNb1RnZVpIU0U3VFIza2t4Y3lpR2ZPUVJUb3pFaTVrMWxRYWwvRUQwVDZEemIxVjhFNElNZEJQeGt0Ci8rQmNXRjdDTEE5bEQzOFNzdXBDSlllZW8wRGw1VlNSRGtqVzBHYm5XVFdwazJna2JVV0VwY3BNVXlCNWh3WDMKRndQTmdXcVlod2ZWdzhlOERuV2N6TkltZ1lkMVkwTE0wZzZ3TGdIZkdqZjZLLzV5S3V2NDZBWVhFTEJaMWprZwpWTTNyZXliK2xYa3Y3OXVsVkprUGFhN1NaUllsMmpRY0FCak1aTzJLVmtTTEpIWEdzVTRFUGJXRTJuV0tBVXpsCkh4bnRzcU12SDVQbXNQbEFRWGF0MG9rM2ViVVFncHI2RmJQbFZlRks1bjlJd2pJTW95ZThWWVcvSFZJRURURmMKYlFJREFRQUIKLS0tLS1FTkQgUFVCTElDIEtFWS0tLS0tCg=="