include:
  - rabbitmq/compose.yaml
  - mockserver/compose.yml
  - eventstoredb/compose.yml
  - payments/compose.yml
  - dinopay-gateway/compose.yml
  - envoy/compose.yml
  - mysql/compose.yml
  - vault/compose.yml
  - redis/compose.yml
  - barong/compose.yml
  - mongodb/compose.yml
  - payments-read-model/compose.yml

