services:
  vault:
    image: vault:1.3.4
    command: [ 'server', '-dev' ]
    ports:
      - "8200:8200"
    environment:
      VAULT_TOKEN: "changeme"
      VAULT_DEV_ROOT_TOKEN_ID: "changeme"
      VAULT_ADDR: "http://127.0.0.1:8200"